name: Move to in review

on:
    pull_request:
        types: [review_requested]
jobs:
    move-to-in-review:
        runs-on: ubuntu-latest
        steps:
            - name: Get linked issue of a PR
              env:
                GITHUB_TOKEN: ${{ secrets.YOUR_ACCESS_TOKEN }}
                ORGANIZATION: LanderDebeir
                PROJECT_NUMBER: 1
                PR_ID: ${{ github.event.pull_request.node_id }}
              run: |
                linked_issue_id="$( gh api graphql -f query='
                query($pr:ID!) {
                    node(id: $pr) {
                        ... on PullRequest {
                            closingIssuesReferences(first:1, userLinkedOnly:false) {
                                totalCount
                                nodes { 
                                    id 
                                    projectItems(first: 5) {
                                        nodes {
                                            id
                                        }
                                    }
                                }
                            }
                        }
                    }
                }' -f pr=$PR_ID --jq '.data.node.closingIssuesReferences.nodes[0].projectItems.nodes[0].id')"
                echo "ISSUE ID:"
                echo "$linked_issue_id"
                echo "PR-ID:"
                echo ${{env.PR_ID}}
                echo "LINKED_ISSUE_ID=$linked_issue_id" >> $GITHUB_ENV  
            - name: Get node id of project
              id: get-project-id
              env:
                GITHUB_TOKEN: ${{ secrets.YOUR_ACCESS_TOKEN }}
                ORGANIZATION: LanderDebeir
                PROJECT_NUMBER: 1
              uses: monry/actions-get-project-id@v2
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                project-owner: ${{ env.ORGANIZATION }}
                project-number: ${{ env.PROJECT_NUMBER }}
            - name: Get node id of status field
              id: get-status-field-id
              env:
                GITHUB_TOKEN: ${{ secrets.YOUR_ACCESS_TOKEN }}
                ORGANIZATION: LanderDebeir
                PROJECT_NUMBER: 1
                STATUS_FIELD_NAME: Status
                OPTION_NAME: In review
              uses: infinite-automations/gh-projects-field-ids@v1.0.0
              with:
                token: ${{ env.GITHUB_TOKEN }}
                project-owner: ${{ env.ORGANIZATION }}
                project-number: ${{ env.PROJECT_NUMBER }}
                field-name: ${{ env.STATUS_FIELD_NAME }}
                select-option-name: ${{ env.OPTION_NAME }}
            - name: fill in environment variables
              run: |
                echo "PROJECT_ID=${{steps.get-project-id.outputs.project-id}}" >> $GITHUB_ENV
                echo "STATUS_FIELD_ID=${{steps.get-status-field-id.outputs.field-id}}" >> $GITHUB_ENV
                echo "IN_REVIEW_OPTION_ID=${{steps.get-status-field-id.outputs.option-id}}" >> $GITHUB_ENV
            - name: Change status to in review
              env:
                GITHUB_TOKEN: ${{ secrets.YOUR_ACCESS_TOKEN }}
                PROJECT_ID: ${{ env.PROJECT_ID }}
                ISSUE_ID: ${{ env.LINKED_ISSUE_ID }} 
                STATUS_FIELD_ID: ${{env.STATUS_FIELD_ID}}
                IN_REVIEW_OPTION_ID: ${{env.IN_REVIEW_OPTION_ID}}
              run: |
                updatedAt="$( gh api graphql -f query='
                mutation($issueId:ID!, $projectId:ID!) {
                    updateProjectV2ItemFieldValue(input: {projectId: $projectId, fieldId: "${{env.STATUS_FIELD_ID}}", itemId: $issueId, value: {singleSelectOptionId: "${{env.IN_REVIEW_OPTION_ID}}"}}) {
                        projectV2Item {
                            type
                            updatedAt
                        }
                    }
                }' -f issueId=$ISSUE_ID -f projectId=$PROJECT_ID --jq '.data.updateProjectV2ItemFieldValue.projectV2Item.updatedAt')"
